const message = {
    channel: {
        type: 'text',
        deleted: false,
        id: '863273868349538346',
        name: 'general',
        rawPosition: 0,
        parentID: '863273868349538344',
        permissionOverwrites: Collection(0)[Map],
        topic: null,
        lastMessageID: '863440920065867826',
        rateLimitPerUser: 0,
        lastPinTimestamp: null,
        guild: {
            members: [GuildMemberManager],
            channels: [GuildChannelManager],
            roles: [RoleManager],
            presences: [PresenceManager],
            voiceStates: [VoiceStateManager],
            deleted: false,
            available: true,
            id: '863273867657216021',
            shardID: 0,
            name: 'Test SErver',
            icon: null,
            splash: null,
            discoverySplash: null,
            region: 'us-east',
            memberCount: 3,
            large: false,
            features: [],
            applicationID: null,
            afkTimeout: 300,
            afkChannelID: null,
            systemChannelID: '863273868349538346',
            embedEnabled: undefined,
            premiumTier: 0,
            premiumSubscriptionCount: 0,
            verificationLevel: 'NONE',
            explicitContentFilter: 'DISABLED',
            mfaLevel: 0,
            joinedTimestamp: 1625891082653,
            defaultMessageNotifications: 'ALL',
            systemChannelFlags: [SystemChannelFlags],
            maximumMembers: 100000,
            maximumPresences: null,
            approximateMemberCount: null,
            approximatePresenceCount: null,
            vanityURLCode: null,
            vanityURLUses: null,
            description: null,
            banner: null,
            rulesChannelID: null,
            publicUpdatesChannelID: null,
            preferredLocale: 'en-US',
            ownerID: '420651836157067275',
            emojis: [GuildEmojiManager]
        },
        messages: {
            cache: [LimitedCollection[Map]],
            channel: [Circular * 1]
        },
        nsfw: false,
    },
    deleted: false,
    id: '863440920065867826',
    type: 'DEFAULT',
    system: false,
    content: '!avatar',
    author: {
        id: '771121569782693888',
        system: null,
        locale: null,
        flags: { bitfield: 0 },
        username: 'testfordev',
        bot: false,
        discriminator: '0195',
        avatar: null,
        lastMessageID: '863440920065867826',
        lastMessageChannelID: '863273868349538346'
    },
    pinned: false,
    tts: false,
    nonce: '863440919536336896',
    embeds: [],
    attachments: Collection(0)[Map],
    createdTimestamp: 1625930757300,
    editedTimestamp: 0,
    reactions: {
        cache: Collection(0)[Map],
        message: [Circular * 2]
    },
    mentions: {
        everyone: false,
        users: Collection(0)[Map],
        roles: Collection(0)[Map],
        _members: null,
        _channels: null,
        crosspostedChannels: Collection(0)[Map]
    },
    webhookID: null,
    application: null,
    activity: null,
    _edits: [],
    flags: { bitfield: 0 },
    reference: null
}